## 2. ndarray创建方式

In [1]:
import numpy as np
from numpy import dtype

### 1. 通过列表或者现有数组创建ndarray

##### 1.1 通过列表创建ndarray， 传递参数为 list，可选参数 dtype

In [2]:
arr_1 = np.array([1,2,3,4,5], dtype=int)
print("arr_1:", arr_1)

arr_1: [1 2 3 4 5]


##### 1.2 通过copy方式，创建ndarray， 传递参数为现有数组

In [4]:
arr_copy = np.copy(arr_1)
print("arr_copy:", arr_copy)

arr_copy: [1 2 3 4 5]


#### 2. 创建固定数值的ndarray

##### 2.1 创建全0数组, 传递参数为 shape，可选参数 dtype

In [5]:
arr_all_zeros = np.zeros((2,3), dtype=float) # 创建2行3列的全0浮点型数组
print("arr_all_zeros:\n", arr_all_zeros)

arr_all_zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


##### 2.2 创建全1数组, 传递参数为 shape，可选参数 dtype

In [6]:
arr_all_ones = np.ones((2,3), dtype=float) # 创建2行3列的全1浮点型数组
print("arr_all_ones:\n", arr_all_ones)

arr_all_ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


##### 2.3 创建指定数值填充的数组，传递参数为 shape 和 fill_value，可选参数 dtype

In [7]:
arr_all_filled = np.full((2,3), fill_value=10, dtype=int) # 创建2行3列的全10整型数组
print("arr_all_filled:\n", arr_all_filled)

arr_all_filled:
 [[10 10 10]
 [10 10 10]]


##### 2.4 创建全空数组，传递参数为 shape，可选参数 dtype，注意：数组内容未初始化，可能包含随机值

In [9]:
arr_all_empty = np.empty((2,3), dtype=float) # 创建2行3列的全空浮点型数组
print("arr_all_empty:\n", arr_all_empty)

arr_all_empty:
 [[0. 0. 0.]
 [0. 0. 0.]]


#### 3. 创建有序数值的ndarray

##### 3.1 使用 arange 创建等差数列，通过步长控制，传递参数为 start, stop(不包含), step，可选参数 dtype

In [11]:
arr_arange = np.arange(0, 10, 2, dtype=int) # 创建从0到10，步长为2的等差数列整型数组
print("arr_arrange:", arr_arange)

arr_arrange: [0 2 4 6 8]


##### 3.2 使用 linspace 创建等差数列，通过指定元素个数控制，传递参数为 start, stop(包含), num，可选参数 dtype


In [12]:
arr_linspace = np.linspace(0, 10, num=5, dtype=int) # 创建从0到10，包含10，元素个数为5的等差数列整型数组
print("arr_linspace:", arr_linspace)

arr_linspace: [ 0  2  5  7 10]


#### 4. 创建随机数值的ndarray

##### 4.1 创建均匀分布的随机数数组，传递参数为 shape

In [13]:
arr_random_uniform = np.random.rand(2,3) # 创建2行3列的均匀分布随机浮点型数组
print(arr_random_uniform)

[[0.89669413 0.33556042 0.63303159]
 [0.36736222 0.54827958 0.89452398]]


##### 4.2 创建标准正态分布的随机数数组，传递参数为 shape

In [15]:
arr_ramdom_normal = np.random.randn(2,3) # 创建2行3列的标准正态分布随机浮点型数组
print(arr_ramdom_normal)

[[-0.95985923 -2.04574595 -0.20622985]
 [-1.98489725 -0.48121237 -1.26423247]]


##### 4.3 创建指定范围内的随机整数数组，传递参数为 low, high(不包含), size(shape)

In [16]:
arr_ramdom_int = np.random.randint(0,10, size=(2,3)) # 创建2行3列的0到10的随机整型数组
print(arr_ramdom_int)

[[9 8 3]
 [3 5 2]]


##### 4.4 固定随机数种子，传递参数为 seed

In [17]:
np.random.seed(10)

#### 5.创建矩阵类型的ndarray

##### 5.1 创建单位矩阵(对角线值为1)，传递参数为 N(行数) M(列数，可选，默认与行数相等)，k 对角线位置，可选参数 dtype

In [21]:
arr_eye = np.eye(3, dtype=int) # 创建3行3列的整型单位矩阵
print("arr_eye:\n", arr_eye)

# 修改对角线位置
arr_eye_k1 = np.eye(5, k=1, dtype=int) # 创建5行5列的整型单位矩阵，对角线位置向上偏移1
print("arr_eye_k1:\n", arr_eye_k1)

arr_eye_k2 = np.eye(5, k=-1, dtype=int) # 创建5行5列的整型单位矩阵，对角线位置向下偏移2
print("arr_eye_k2:\n", arr_eye_k2)

arr_eye:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
arr_eye_k1:
 [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
arr_eye_k2:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


##### 5.2 创建对角矩阵， 传递参数为对角线元素的1维数组，可选参数 k 对角线位置

##### 5.2.1 参数为1维数组，则创建对角线矩阵

In [25]:
arr_diag_1d = np.diag([1,2,3,4,5], k=0) # 创建对角线元素为1,2,3,4,5的整型对角矩阵
print("arr_diag_1d:\n", arr_diag_1d)

# k 对角线位置偏移
arr_diag_1d_k1 = np.diag([1,2,3,4,5], k=1) # 创建对角线元素为1,2,3,4,5的整型对角矩阵，对角线位置向上偏移1
print("arr_diag_1d_k1:\n", arr_diag_1d_k1)

arr_diag_1d:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
arr_diag_1d_k1:
 [[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


##### 5.2.2 参数为2维数组，则提取这个参数的对角线元素，返回1维数组

In [28]:
matrix = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]]
arr_diag_2d = np.diag(matrix, k=0) # 提取matrix的对角线元素，返回1维数组
print("arr_diag_2d:", arr_diag_2d)

arr_diag_2d: [ 1  7 13 19 25]
