## 3. ndarray的数据类型dtype

### 1. dtype的向上转换规则

In [2]:
import numpy as np

arr_1 = np.array([1, 2, 3.5]) # 整数和浮点数混合，整数向上转换为浮点数
print("Type of arr_1 is:",arr_1.dtype)
print("Itemsize of arr_1 is:",arr_1.itemsize)
print("Nbytes of arr_1 is:",arr_1.nbytes)

Type of arr_1 is: float64
Itemsize of arr_1 is: 8
Nbytes of arr_1 is: 24


### 2. 指定dtype创建ndarray
**尽量使用 int32，float32**

##### 2.1 int32

In [3]:
arr_2 = np.array([1,2,3], dtype = np.int32) # 如果直接写int，默认为64位
print(arr_2)
print("Type of arr_2 is:", arr_2.dtype)
print("Itemsize of arr_2 is:", arr_2.itemsize)
print("Total bytes of arr_2 is:", arr_2.nbytes)

[1 2 3]
Type of arr_2 is: int32
Itemsize of arr_2 is: 4
Total bytes of arr_2 is: 12


##### 2.2 float32

In [4]:
arr_3 = np.array([1.0, 2.0, 3.0], dtype = np.float32) # 如果直接写float，默认为64位
print(arr_3)
print("Type of arr_3 is:", arr_3.dtype)
print("Itemsize of arr_3 is:", arr_3.itemsize)
print("Total bytes of arr_3 is:", arr_3.nbytes)

[1. 2. 3.]
Type of arr_3 is: float32
Itemsize of arr_3 is: 4
Total bytes of arr_3 is: 12


##### 2.3 bool

In [5]:
arr_4 = np.array([1, 0, 2, -3], dtype = np.bool_) # 非0即True，0为False
print(arr_4)
print("Type of arr_4 is:", arr_4.dtype)
print("Itemsize of arr_4 is:", arr_4.itemsize)
print("Total bytes of arr_4 is:", arr_4.nbytes)

[ True False  True  True]
Type of arr_4 is: bool
Itemsize of arr_4 is: 1
Total bytes of arr_4 is: 4


### 3. 修改dtype
**注意：astype修改之后不会修改原ndarray，而是返回一个新的ndarray**

In [6]:
arr_5 = arr_4.astype(np.float32)
print(arr_5)
print("Type of arr_5 is:", arr_5.dtype)
print("Itemsize of arr_5 is:", arr_5.itemsize)
print("Total bytes of arr_5 is:", arr_5.nbytes)

[1. 0. 1. 1.]
Type of arr_5 is: float32
Itemsize of arr_5 is: 4
Total bytes of arr_5 is: 16


In [7]:
arr_6 = arr_3.astype(np.int32)
print(arr_6)
print("Type of arr_6 is:", arr_6.dtype)
print("Itemsize of arr_6 is:", arr_6.itemsize)
print("Total bytes of arr_6 is:", arr_6.nbytes)

[1 2 3]
Type of arr_6 is: int32
Itemsize of arr_6 is: 4
Total bytes of arr_6 is: 12
