## 5. ndarray的计算

#### 1. 元素级别的算术运算
**返回值为一个新的ndarray，原ndarray不变**

##### 1.1 数组&数组

In [2]:
import numpy as np

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
print("arr_1 + arr_2 =", arr_1 + arr_2) # 加法
print("arr_1 - arr_2 =", arr_1 - arr_2) #
print("arr_1 * arr_2 =", arr_1 * arr_2) # 乘法
print("arr_1 / arr_2 =", arr_1 / arr_2) # 除法
print("arr_1 // arr_2 =", arr_1 // arr_2) # 整除
print("arr_1 % arr_2 =", arr_1 % arr_2) # 取模
print("arr_1 ** 2 =", arr_1 ** 2) # 幂运算

arr_2d_1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr_2d_2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print("arr_2d_1 + arr_2d_2 =\n", arr_2d_1 + arr_2d_2)
print("arr_2d_1 - arr_2d_2 =\n", arr_2d_1 - arr_2d_2)
print("arr_2d_1 * arr_2d_2 =\n", arr_2d_1 * arr_2d_2)
print("arr_2d_1 / arr_2d_2 =\n", arr_2d_1 / arr_2d_2)
print("arr_2d_1 // arr_2d_2 =\n", arr_2d_1 // arr_2d_2)
print("arr_2d_1 % arr_2d_2 =\n", arr_2d_1 % arr_2d_2)
print("arr_2d_1 ** 2 =\n", arr_2d_1 ** 2)


arr_1 + arr_2 = [5 7 9]
arr_1 - arr_2 = [-3 -3 -3]
arr_1 * arr_2 = [ 4 10 18]
arr_1 / arr_2 = [0.25 0.4  0.5 ]
arr_1 // arr_2 = [0 0 0]
arr_1 % arr_2 = [1 2 3]
arr_1 ** 2 = [1 4 9]
arr_2d_1 + arr_2d_2 =
 [[ 8 10 12]
 [14 16 18]]
arr_2d_1 - arr_2d_2 =
 [[-6 -6 -6]
 [-6 -6 -6]]
arr_2d_1 * arr_2d_2 =
 [[ 7 16 27]
 [40 55 72]]
arr_2d_1 / arr_2d_2 =
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
arr_2d_1 // arr_2d_2 =
 [[0 0 0]
 [0 0 0]]
arr_2d_1 % arr_2d_2 =
 [[1 2 3]
 [4 5 6]]
arr_2d_1 ** 2 =
 [[ 1  4  9]
 [16 25 36]]


##### 1.2 数组&标量

In [3]:
print("arr_1 + 10 = ", arr_1 + 10) # 加法
print("arr_1 - 10 = ", arr_1 - 10) # 减法
print("arr_1 * 10 = ", arr_1 * 10) # 乘法
print("arr_1 / 10 = ", arr_1 / 10) # 除法
print("arr_1 // 10 = ", arr_1 // 10) # 整除
print("arr_1 % 10 = ", arr_1 % 10) # 取模
print("arr_1 ** 2 = ", arr_1 ** 2) # 幂运算

arr_1 + 10 =  [11 12 13]
arr_1 - 10 =  [-9 -8 -7]
arr_1 * 10 =  [10 20 30]
arr_1 / 10 =  [0.1 0.2 0.3]
arr_1 // 10 =  [0 0 0]
arr_1 % 10 =  [1 2 3]
arr_1 ** 2 =  [1 4 9]


#### 2. 常用数学函数

##### 2.1 常见数学函数

In [4]:
print("arr_1 的平方根：",np.sqrt(arr_1))
print("arr_1 的的平方：",np.square(arr_1))
print("arr_1 的指数函数：", np.exp(arr_1))
print("arr_1 的自然对数：", np.log(arr_1))
print("arr_1 的以10为底的对数：", np.log10(arr_1))
print("arr_1 的以2为底的对数：", np.log2(arr_1))

arr_1 的平方根： [1.         1.41421356 1.73205081]
arr_1 的的平方： [1 4 9]
arr_1 的指数函数： [ 2.71828183  7.3890561  20.08553692]
arr_1 的自然对数： [0.         0.69314718 1.09861229]
arr_1 的以10为底的对数： [0.         0.30103    0.47712125]
arr_1 的以2为底的对数： [0.        1.        1.5849625]


##### 2.2 三角函数（返回值均为弧度制）

In [5]:
print("arr_1 的sin值：", np.sin(arr_1))
print("arr_1 的cos值：", np.cos(arr_1))
print("arr_1 的tan值：", np.tan(arr_1))
print("arr_1 的arcsin值：", np.arcsin(arr_1/10)) # 注意：arcsin的输入值范围为[-1,1]
print("arr_1 的arccos值：", np.arccos(arr_1/10)) # 注意：arccos的输入值范围为[-1,1]
print("arr_1 的arctan值：", np.arctan(arr_1))

arr_1 的sin值： [0.84147098 0.90929743 0.14112001]
arr_1 的cos值： [ 0.54030231 -0.41614684 -0.9899925 ]
arr_1 的tan值： [ 1.55740772 -2.18503986 -0.14254654]
arr_1 的arcsin值： [0.10016742 0.20135792 0.30469265]
arr_1 的arccos值： [1.47062891 1.36943841 1.26610367]
arr_1 的arctan值： [0.78539816 1.10714872 1.24904577]


#### 3. 比较运算（返回 bool 数组） & 逻辑运算 （必须使用逻辑运算符）

##### 3.1 比较运算

In [7]:
print("arr_1中的元素是否大于2：", arr_1 > 2)

arr_1中的元素是否大于2： [False False  True]


##### 3.2 逻辑运算

In [9]:
print("arr_1中的元素是否大于2且小于：", (arr_1 > 2) & (arr_1 < 5))
print("arr_1中的元素是否大于2或小于等于2：", (arr_1 > 2) | (arr_1 <= 2))

arr_1中的元素是否大于2且小于： [False False  True]
arr_1中的元素是否大于2或小于等于2： [ True  True  True]


#### 4. 矩阵运算，注意：行和列必须匹配

In [11]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])
print("A 与 B 中的元素逐个相乘：", A * B) # 元素逐个相乘
print("A 与 B 的矩阵乘法：", A @ B ) # 或者 np.dot(A, B)

A 与 B 中的元素逐个相乘： [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
A 与 B 的矩阵乘法： [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


#### 5. 聚合函数

In [12]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

##### 5.1 按照行聚合

In [15]:
print("sum: ", np.sum(arr, axis=1)) # 返回按照行集合之后的集合
print("max: ", np.max(arr)) # 返回整个ndarray的最大值
print("min: ", np.min(arr)) # 返回整个ndarray的最小值
print("mean: ", np.mean(arr)) # 返回整个ndarray的均值
print("median: ", np.median(arr)) # 返回整个ndarray的中位数
print("std: ", np.std(arr)) # 返回整个ndarray的标准差
print("var: ", np.var(arr)) # 返回整个ndarray的方差

sum:  [ 6 15 24]
max:  9
min:  1
mean:  5.0
median:  5.0
std:  2.581988897471611
var:  6.666666666666667


##### 5.2 按照列聚合

In [16]:
print("sum: ", np.sum(arr, axis=0))

sum:  [12 15 18]
