## 1.1 Tensor 的创建方式

#### 1. 张量的基本创建方式

##### 1.1 从python数据创建

In [1]:
import torch
import numpy as np
# 创建0维张量
a = torch.tensor(1)

# 创建1维张量
b = torch.tensor([1, 2, 3])

# 创建2维张量
c = torch.tensor([[1, 2],
                 [3, 4]])

data = np.random.randint(0,10, size=(2,3))
d = torch.tensor(data)

print(a)
print(b)
print(c)
print(d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[7, 8, 2],
        [9, 0, 1]])


##### 1.2 指定数据类型创建并且查看数据类型

In [ ]:
a = torch.tensor(1, dtype=torch.float32)
print(a.dtype)

##### 1.3 使用 Tensor 方式创建张量
参数为数据或者形状，数据类型默认为float32
注意：如果只传递一个参数，则表示创建一个长度为该参数的1维张量，默认数据类型为float32；而不是创建一个标量

In [7]:
a = torch.Tensor(1) # 默认是float32
print(a)
print(a.dtype)

b = torch.Tensor(2,3) # 创建一个2行3列的张量，默认数据类型为float32
print(b)

c = torch.Tensor([1,2,3])
print(c)
print(c.dtype)

tensor([8.7348e-33])
torch.float32
tensor([[8.6766e-33, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
tensor([1., 2., 3.])
torch.float32


#### 2. 创建全0张量、全1张量

In [3]:
# 全0
e = torch.zeros((2,3))
print(e)
# 全1
f = torch.ones((2,3))
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### 3. 创建线性序列张量

##### 3.1 arange 类似于python的range函数和numpy的arange函数

In [4]:
# 从0到10，步长为2
g = torch.arange(0,10, step=2)
print(g)

tensor([0, 2, 4, 6, 8])


##### 3.2 linspace 在指定范围内生成等差数列, 类似于numpy的linspace函数

In [5]:
# 从0到10，生成5个数
h = torch.linspace(0,10, steps=5)
print(h)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


#### 4. 创建随机张量

##### 4.1 设置随机数种子，保证每次运行生成的随机数相同

In [35]:
# torch.manual_seed(42)
# # 如果使用GUP，还需要设置GPU的随机数种子
# if torch.cuda.is_available():
#     torch.cuda.manual_seed(42)
#     torch.cuda.manual_seed_all(42)

# 更严的随机数生成器设置
# Python，NumPy和PyTorch的随机数生成器都设置为相同的种子
import random
import numpy as np

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)


##### 4.2 rand 创建均匀分布的随机数张量（0-1）

In [38]:
i = torch.rand(2,3)
print(i)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


##### 4.3 randn 创建标准正态分布的随机数张量（均值为0，标准差为1）

In [39]:
j = torch.randn(2,3)
print(j)

tensor([[ 0.3930,  0.4327, -1.3627],
        [ 1.3564,  0.6688, -0.7077]])


##### 4.4 randint 创建指定范围内的随机整数张量

In [40]:
k = torch.randint(0,10, size=(2,3))
print(k)

tensor([[2, 0, 5],
        [9, 3, 4]])


#### 5. 元素类型转换

In [28]:
# 将整数张量转换为浮点数张量
k = k.to(torch.float)
print(k)

# 直接方法
k = k.int()
print(k)

tensor([[7., 6., 9.],
        [6., 3., 1.]])
tensor([[7, 6, 9],
        [6, 3, 1]], dtype=torch.int32)


#### 6. 查看常见属性

In [10]:
# 查看张量的形状
print(k.shape)
# 查看张量的维度
print(k.ndim)
# 查看张量的数据类型
print(k.dtype)
# 查看张量所在的设备
print(k.device)

torch.Size([2, 3])
2
torch.int32
cpu
