## 1.1 Tensor 的创建方式

#### 1. 张量的基本创建方式

##### 1.1 从python数据创建

In [4]:
import torch
import numpy as np
# 创建0维张量
a = torch.tensor(1)

# 创建1维张量
b = torch.tensor([1, 2, 3])

# 创建2维张量
c = torch.tensor([[1, 2],
                  [3, 4]])

data = np.random.randint(0,10, size=(2,3))
d = torch.tensor(data)

print(a)
print(b)
print(c)
print(d)

tensor([1409.0897])
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[5, 9, 7],
        [4, 5, 8]])


##### 1.2 指定数据类型创建并且查看数据类型

In [2]:
a = torch.tensor(1, dtype=torch.float32)
print(a.dtype)

torch.float32


#### 2. 创建全0张量、全1张量

In [5]:
# 全0
e = torch.zeros((2,3))
print(e)
# 全1
f = torch.ones((2,3))
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### 3. 创建线性序列张量

##### 3.1 arange 类似于python的range函数和numpy的arange函数

In [6]:
# 从0到10，步长为2
g = torch.arange(0,10, step=2)
print(g)

tensor([0, 2, 4, 6, 8])


##### 3.2 linspace 在指定范围内生成等差数列, 类似于numpy的linspace函数

In [8]:
# 从0到10，生成5个数
h = torch.linspace(0,10, steps=5)
print(h)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


#### 4. 创建随机张量

##### 4.1 rand 创建均匀分布的随机数张量（0-1）

In [9]:
i = torch.rand(2,3)
print(i)

tensor([[0.6835, 0.9110, 0.6626],
        [0.0196, 0.0762, 0.5447]])


##### 4.2 randn 创建标准正态分布的随机数张量（均值为0，标准差为1）


In [10]:
j = torch.randn(2,3)
print(j)

tensor([[ 1.3289,  1.3360, -1.4769],
        [ 1.0064,  0.9690,  1.5060]])


##### 4.3 randint 创建指定范围内的随机整数张量

In [11]:
k = torch.randint(0,10, size=(2,3))
print(k)

tensor([[0, 2, 9],
        [2, 9, 0]])


#### 5. 元素类型转换

In [12]:
# 将整数张量转换为浮点数张量
k = k.to(torch.float)
print(k)

# 直接方法
k = k.int()
print(k)

tensor([[0., 2., 9.],
        [2., 9., 0.]])
tensor([[0, 2, 9],
        [2, 9, 0]], dtype=torch.int32)


#### 6. 查看常见属性

In [15]:
# 查看张量的形状
print(k.shape)
# 查看张量的维度
print(k.ndim)
# 查看张量的数据类型
print(k.dtype)
# 查看张量所在的设备
print(k.device)

torch.Size([2, 3])
2
torch.int32
cpu
