## 2. Tensor 类型转换

#### 1. 从 Numpy 转换为 Tensor

##### 1.1 torch.from_numpy() 函数：
1. 共享内存
2. 不复制数据
3. 修改其中一个会影响另一个
4. 浅拷贝

In [1]:
import numpy as np
import torch

arr_1 = np.array([1,2,3,4,5])
data_1 = torch.from_numpy(arr_1)

print(data_1)

tensor([1, 2, 3, 4, 5])


In [2]:
arr_1[0] = 100
print(data_1)

tensor([100,   2,   3,   4,   5])


##### 1.2 torch.tensor() 函数：
1. 不共享内存
2. 复制数据
3. 修改其中一个不会影响另一个
4. 深拷贝

In [3]:
arr_2 = np.array([10,20,30,40,50])
data_2 = torch.tensor(arr_2)
print(data_2)

tensor([10, 20, 30, 40, 50])


In [5]:
arr_2[0] = 100
print(data_2)

tensor([10, 20, 30, 40, 50])


#### 2. 从 Tensor 转换为 Numpy

##### 2.1 基本转换 tensor.numpy() 函数:
1. 共享内存
2. 不复制数据
3. 修改其中一个会影响另一个
4. 浅拷贝

In [6]:
data_3 = torch.tensor([1,2,3,4,5])
arr_3 = data_3.numpy()
print(arr_3)

[1 2 3 4 5]


In [7]:
data_3[0] = 100
print(arr_3)

[100   2   3   4   5]


##### 2.2 torch.detach.cpu().numpy() 函数:
1. 同样是浅拷贝
2. 如果 Tensor 在 GPU 上，则需要先将其移动到 CPU 上，然后再转换为 Numpy 数组
3. 因为 GPU 上的 Tensor 不能直接转换为 Numpy 数组，所以需要先将其移动到 CPU 上

In [10]:
arr_4 = data_3.detach().cpu().numpy()
print(arr_4)

[100   2   3   4   5]


##### 2.3 torch.numpy().copy() 函数，本质上是先调用 torch.numpy() 函数获取一个共享内存的 Numpy 数组，然后再调用 copy() 方法创建一个新的 Numpy 数组，从而实现深拷贝。
1. 不共享内存
2. 复制数据
3. 修改其中一个不会影响另一个
4. 深拷贝

In [11]:
data_5 = torch.tensor([2,4,6,8,10])
arr_5 = data_5.numpy().copy()
print(arr_5)

[ 2  4  6  8 10]


In [12]:
data_5[0] = 100
print(arr_5)

[ 2  4  6  8 10]


#### 3. Tensor 转换为 标量

##### 3.1 从 python 标量转换为 0维张量，torch.tensor() 函数：

In [14]:
data_6 = torch.tensor(1)
print(data_6)
print(data_6.shape)

tensor(1)
torch.Size([])


##### 3.2 从 0维张量转换为 python 标量，item() 函数：
1. 只能用于0维张量
2. 返回一个 Python 标量

In [15]:
x = data_6.item()
print(x)

1


#### 4 Tensor 的 clone() 方法：
1. 创建一个新的 Tensor，数据与原 Tensor 相同，但不共享内存，深拷贝
2. 修改其中一个不会影响另一个

In [17]:
arr_7 = np.array([1,2,3,4,5])
data_7 = torch.tensor(arr_7).clone()
print(data_7)

tensor([1, 2, 3, 4, 5])


In [18]:
arr_7[0] = 100
print(data_7)

tensor([1, 2, 3, 4, 5])
