## 3.1 Tensor 运算 - 基本运算

#### 1. + - * / 四则运算

##### 1.1 +

In [5]:
import torch
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a + b)

tensor([5, 7, 9])


##### 1.2 -

In [2]:
print(a - b)

tensor([-3, -3, -3])


##### 1.3 *

In [3]:
print(a * b)

tensor([ 4, 10, 18])


##### 1.4 /

In [4]:
print(a / b)

tensor([0.2500, 0.4000, 0.5000])


#### 2. 张量与标量的运算：
依赖于广播机制，标量会自动扩展为与张量相同的形状，然后进行逐元素运算。

In [7]:
a = torch.tensor([1,2,3])
print(a * 2) # 每个元素都乘以2
print(a + 5) # 每个元素都加上5
print(a - 1) # 每个元素都减去1
print(a / 2) # 每个元素都除以2

# 等价于将 标量1 扩展为与张量a相同的形状 [1,1,1]，然后进行逐元素运算

tensor([2, 4, 6])
tensor([6, 7, 8])
tensor([0, 1, 2])
tensor([0.5000, 1.0000, 1.5000])


In [8]:
b = torch.tensor([
    [1,2,3],
    [4,5,6]
])

c = torch.tensor([10,20,30])

print(b + c)

tensor([[11, 22, 33],
        [14, 25, 36]])


#### 3. 广播机制：
1. 当两个张量的形状不同时，PyTorch会自动进行广播，使得它们具有相同的形状，从而可以进行逐元素运算。
2. 广播的规则如下：
  - 比较2个张量的维度的最后一个维度
    - 比如上一个例子中，比较(2,3) 和 (,3)，最后一个维度都是3
  - 如果最后一个维度相等，或者其中一个维度为1，则认为它们是兼容的，可以进行广播

#### 4. 原地操作：
1. 在numpy pandas中，原地操作的参数是 inplace=True
2. 在PyTorch中，原地操作的函数名称以 _ 结尾，比如 add_()、mul_()、div_() 等。
3. 原地操作会直接修改原始张量的值，而不是返回一个新的张量。

In [9]:
data = torch.tensor([1,2,3])
data_add = data.add(10) # 返回一个新的张量，原始张量不变
print("Data:", data)
print("Data + 10:", data_add)

Data: tensor([1, 2, 3])
Data + 10: tensor([11, 12, 13])


In [10]:
data_inplace = data.add_(10) # 原地操作，直接修改原始张量的值
print("Data:", data)
print("Data + 10 (in-place):", data_inplace)

Data: tensor([11, 12, 13])
Data + 10 (in-place): tensor([11, 12, 13])


#### 5. 常用数学函数：

In [11]:
# 幂运算
print(torch.pow(data,2))
# 平方根
print(torch.sqrt(data))
# 指数函数
print(torch.exp(data))
# 对数函数
print(torch.log(data))
# 三角函数
print(torch.sin(data))
print(torch.cos(data))
print(torch.tan(data))

tensor([121, 144, 169])
tensor([3.3166, 3.4641, 3.6056])
tensor([ 59874.1406, 162754.7969, 442413.4062])
tensor([2.3979, 2.4849, 2.5649])
tensor([-1.0000, -0.5366,  0.4202])
tensor([0.0044, 0.8439, 0.9074])
tensor([-225.9509,   -0.6359,    0.4630])


#### 6. 比较运算：
1. 比较运算符：==、!=、>、<、>=、<=
2. 返回一个布尔类型的张量，表示每个元素的比较结果

In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([3,2,1])
print(a == b) # [False, True, False]
print(a != b) # [True, False, True]
print(a > b)  # [False, False, True]
print(a < b)  # [True, False, False]
print(a >= b) # [False, True, True]
print(a <= b) # [True, True, False]

tensor([False,  True, False])
tensor([ True, False,  True])
tensor([False, False,  True])
tensor([ True, False, False])
tensor([False,  True,  True])
tensor([ True,  True, False])


#### 7. 逻辑运算：
1. 逻辑运算符：&（与）、|（或）、~（非）
2. 返回一个布尔类型的张量，表示每个元素的逻辑运算结果

In [13]:
a = torch.tensor([True, False, True])
b = torch.tensor([False, False, True])
print(a & b) # [False, False, True]
print(a | b) # [True, False, True]
print(~a)    # [False, True, False]

tensor([False, False,  True])
tensor([ True, False,  True])
tensor([False,  True, False])


#### 8. 统计函数：
1. 常用的统计函数包括：sum()、mean()、std()、var()、min()、max()等
2. 这些函数可以对张量的元素进行统计计算，返回一个标量或者一个新的张量
啊#%%a  md


In [15]:
data = torch.tensor([[1,2,3],
                     [4,5,6]],dtype=torch.float32)
print("Sum:", data.sum()) # 所有元素的和
print("Mean:", data.mean().float()) # 所有元素的平均值
print("Std:", data.std()) # 所有元素的标准差
print("Var:", data.var()) # 所有元素的方差
print("Min:", data.min()) # 所有元素的最小值
print("Max:", data.max()) # 所有元素的最大值

Sum: tensor(21.)
Mean: tensor(3.5000)
Std: tensor(1.8708)
Var: tensor(3.5000)
Min: tensor(1.)
Max: tensor(6.)
