## 3.3 Tensor 运算 - 张量索引操作

#### 1. Shape 的核心概念：
1. 1D张量：shape = (3,)，只有一个维度，包含3个元素，但是必须加逗号表示这是一个一维张量，否则会被认为是一个标量
2. 2D张量：shape = (2,3)，两个维度，第一项表示行，第二项表示列
3. 3D张量：shape = (2,2,3)，三个维度，第一项表示有2个二维张量，每个二维张量有2行3列
4. 4D张量：shape = (2,2,2,3)，常见于CNN中（channel, R, G, B；或者 batch, channel, height, width），第一项表示有2个三维张量，每个三维张量有2个二维张量，每个二维张量有2行3列

#### 2. 索引的基本操作 - 访问元素：
1. 访问单个元素：使用方括号 []，按照维度顺序访问元素
2. 访问行/列：使用冒号 : 来表示访问整个维度

In [3]:
import torch
a = torch.tensor([
    [1,2,3],
    [4,5,6]
])
# 访问单个元素
print(a[0,0]) # 访问第一行第一列的元素，输出1
print(a[1,2]) # 访问第二行第三列的元素，输出6

# 访问行/列
# 访问第一行，所有列
print(a[1])
# 访问所有行，第一列
print(a[:,1])

tensor(1)
tensor(6)
tensor([4, 5, 6])
tensor([2, 5])


#### 3. 索引的切片操作 - 访问子张量：
1. 切片操作：使用冒号 : 来表示切片，按照维度顺序访问子张量
2. 切片的语法：start:stop:step，表示从start开始到stop结束，步长为step
3. 注意：stop 是切片的结束位置，**不包含**stop位置的元素

In [4]:
import numpy as np
data = np.random.randint(low=1, high=10, size=(3,3))

b = torch.tensor(data)
# 访问第0行到第1行，所有列
print(b[0:2, :])
# 访问第0行到第1行，第1列到第2列
print(b[0:2, 1:3])

tensor([[8, 2, 3],
        [4, 3, 8]])
tensor([[2, 3],
        [3, 8]])


#### 4. 省略号索引操作：
1. 省略号 ... 可以用来表示多个冒号 :，当维度较多时，使用省略号表示所有的维度
2. 省略号 ... 可以用来简化多维张量的索引

In [5]:
data_2 = np.random.randint(low=1, high=100, size=(5,5,5,5)) # (batch, channel, height, width)
c = torch.tensor(data_2)

# 取所有的 batch, channel, 访问 height 的第0行和第1行，访问 width 的第0列和第1列
print(c[..., 0:2, 0:2]) # 等价于 c[:, :, 0:2, 0:2]

tensor([[[[ 2, 25],
          [98, 17]],

         [[17, 69],
          [13,  6]],

         [[81,  7],
          [70, 96]],

         [[59, 19],
          [ 7, 35]],

         [[49, 74],
          [ 2, 55]]],


        [[[93, 16],
          [43, 11]],

         [[ 3,  6],
          [86, 54]],

         [[37, 33],
          [24,  7]],

         [[ 3, 56],
          [38, 44]],

         [[ 3, 62],
          [42, 96]]],


        [[[39, 21],
          [78, 77]],

         [[58, 16],
          [ 2, 29]],

         [[98, 58],
          [22, 10]],

         [[73, 31],
          [94, 29]],

         [[53, 27],
          [93, 74]]],


        [[[34, 12],
          [79, 69]],

         [[93, 76],
          [29, 99]],

         [[63, 60],
          [36, 45]],

         [[10, 59],
          [37,  3]],

         [[68, 95],
          [54, 21]]],


        [[[52, 34],
          [77, 41]],

         [[45, 75],
          [44, 84]],

         [[69, 17],
          [59, 51]],

         [[82, 26],
      

#### 5. 布尔索引操作：
1. 布尔索引：使用布尔条件来索引张量，返回满足条件的元素
2. 布尔索引的语法：tensor[condition]，其中 condition 是一个布尔张量，表示每个元素是否满足条件

In [6]:
d = torch.randint(low=1, high=100, size=(5,5,5))
# 取出所有大于50的元素
condition = d > 50 # condition 是一个布尔张量，表示每个元素是否大于50
print(condition)
print(d[condition]) # 取出满足条件的元素，输出一个张量，包含所有大于50的元素

tensor([[[ True, False, False, False, False],
         [ True,  True, False, False,  True],
         [False, False, False, False, False],
         [False,  True, False, False, False],
         [ True,  True, False,  True, False]],

        [[ True,  True,  True, False,  True],
         [ True,  True, False, False,  True],
         [ True, False, False, False,  True],
         [False,  True, False, False, False],
         [ True,  True,  True, False,  True]],

        [[False, False, False, False,  True],
         [ True, False, False,  True,  True],
         [ True,  True, False,  True,  True],
         [ True,  True,  True, False,  True],
         [False,  True, False,  True,  True]],

        [[ True, False,  True, False,  True],
         [ True, False, False,  True, False],
         [ True,  True, False, False,  True],
         [False,  True,  True, False, False],
         [False,  True, False,  True, False]],

        [[False, False, False,  True,  True],
         [False,  True,  T

##### ⚠️注意： 布尔索引返回的结果是一个一维张量，包含所有满足条件的元素，而不是原始张量的形状。
1. 在绝大多数情况下，满足条件的元素在原张量中的分布是随机且不规则的。
2. 索引的本质是“提取”，而提取出的满足要求的元素无法重新拼凑成一个完整的原始形状的矩阵。
3. 为了避免“不规则阵列”（Ragged Tensors）

In [7]:
# 如果需要保持原始的形状：
# 1. 可以使用 torch.where() 函数来返回满足条件的元素的索引，然后使用这些索引来访问原始张量
d_filter = torch.where(condition, d, 50) # 满足条件的元素保留原值，不满足条件的元素替换为50
print(d_filter) # 输出一个与原始张量形状相同的张量，满足条件的元素保留原值，不满足条件的元素替换为50

tensor([[[97, 50, 50, 50, 50],
         [85, 94, 50, 50, 55],
         [50, 50, 50, 50, 50],
         [50, 74, 50, 50, 50],
         [72, 82, 50, 91, 50]],

        [[68, 93, 51, 50, 99],
         [80, 88, 50, 50, 53],
         [92, 50, 50, 50, 59],
         [50, 87, 50, 50, 50],
         [82, 91, 75, 50, 78]],

        [[50, 50, 50, 50, 82],
         [75, 50, 50, 58, 92],
         [96, 80, 50, 81, 51],
         [60, 73, 56, 50, 65],
         [50, 89, 50, 55, 63]],

        [[86, 50, 64, 50, 90],
         [94, 50, 50, 76, 50],
         [52, 96, 50, 50, 57],
         [50, 62, 58, 50, 50],
         [50, 61, 50, 94, 50]],

        [[50, 50, 50, 82, 73],
         [50, 92, 78, 50, 69],
         [50, 50, 88, 50, 67],
         [62, 98, 50, 50, 50],
         [50, 50, 50, 89, 50]]])


#### 6. 花式索引：
1. 使用数组作为索引，来选取不同的元素

In [8]:
e = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

##### 6.1 单个索引张量 -> 作用与对应维度
1. 索引张量只作用于他被使用时所在的那个维度
2. 不需要和原始张量的形状匹配

In [9]:
idx = torch.tensor([0,2]) 
print(e[idx]) # idx 被使用时，所在的维度为行（第一个参数），所以输出的是第0行和第2行的元素，即 [[1,2,3], [7,8,9]]

tensor([[1, 2, 3],
        [7, 8, 9]])


##### 6.2 多个索引张量 -> 逐项匹配
1. 当多个索引张量同时出现时，
2. 他们会按“位置一一配对”来索引
3. 依次分别从 row 和 col 中选出第i个 row 和 col
4. 而不是先选所有的 row 再选所有的 col，而是：
5. 第 i 个 row 配对 第 i 个 col

In [10]:
row = torch.tensor([0,2])
col = torch.tensor([1,2])
print(e[row, col]) # 输出 [2,9]，第1个 row 配对 第1个 col（e[0,1]），第2个 row 配对 第2个 col（e[2,2]）

tensor([2, 9])


#### 7. None 索引
1. 使用 None 索引临时在原始张量上增加一个维度
2. 很多时候为了做 广播/矩阵乘法，需要将张量增加维度

In [12]:
f = torch.tensor([1,2,3])
print(f[None,:])
print(f[None,:].shape) # 输出 torch.Size([1, 3])，在第0维添加了一个新的维度
print(f[:,None])
print(f[:,None].shape) # 输出 torch.Size([3, 1])，在第1维添加了一个新的维度

tensor([[1, 2, 3]])
torch.Size([1, 3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


#### 8. take 方法 - 按照扁平索引取值
1. take 方法会将tensor当作1维

In [13]:
g = torch.tensor([
    [1,2,3],
    [4,5,6]
])
idx = torch.tensor([0,2])
print(torch.take(g, idx)) # 输出 [1,3]，torch.take() 函数会将输入张量展平为一维，然后根据提供的索引返回对应的元素。这里 idx 中的 0 对应 g 中的第一个元素 1，idx 中的 2 对应 g 中的第三个元素 3，因此输出 [1,3]。

tensor([1, 3])


#### 9. 索引返回的是“视图”还是“拷贝”？（必须知道）⚠️
1. 切片 slice 通常是 view（共享内存）
2. 布尔索引/花式索引 返回的是一个新的张量