## 0) Setup

In [1]:

import numpy as np

np.__version__


'2.3.4'


## 1) Array Creation Basics

NumPy arrays are **homogeneous** (all elements share the same dtype) and support efficient vectorized operations.


In [2]:

# From Python lists
a = np.array([1, 2, 3], dtype=np.int64)
b = np.array([[1, 2, 3],[4, 5, 6]], dtype=float)

print("a:", a, "dtype:", a.dtype, "shape:", a.shape)
print("b:\n", b, "\ndtype:", b.dtype, "shape:", b.shape)

# Built-ins
zeros = np.zeros((2,3))
ones  = np.ones((2,3))
ar    = np.arange(0, 10, 2)      # step-based
lin   = np.linspace(0, 1, 5)     # count-based
eye   = np.eye(3)                # identity

zeros, ones, ar, lin, eye


a: [1 2 3] dtype: int64 shape: (3,)
b:
 [[1. 2. 3.]
 [4. 5. 6.]] 
dtype: float64 shape: (2, 3)


(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))


## 2) Shape, Reshape, Ravel

- `reshape` changes view if possible (no copy).
- `ravel` gives a flattened **view** when possible; `flatten` always copies.


In [4]:

x = np.arange(12)
x2 = x.reshape(3,4)
x_ravel = x2.ravel()
x_flatten = x2.flatten()

print("x:", x)
print("x2 shape:", x2.shape)

x2[0,0] = 999
print("After modifying x2[0,0] ->", x[0], "(reflects view)")


x: [ 0  1  2  3  4  5  6  7  8  9 10 11]
x2 shape: (3, 4)
After modifying x2[0,0] -> 999 (reflects view)


In [5]:
x_ravel

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [6]:
x_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## 3) Broadcasting

Broadcasting lets NumPy perform arithmetic on arrays of different shapes, following alignment rules.


In [7]:

X = np.arange(6).reshape(2,3)
col = np.array([[10],[20]])  # shape (2,1)
row = np.array([100,200,300])  # shape (3,)

print("X:\n", X)
print("Add column vector:\n", X + col)
print("Add row vector:\n", X + row)
print("Outer sum via broadcasting:\n", col + row)  # (2,1)+(3,) -> (2,3)


X:
 [[0 1 2]
 [3 4 5]]
Add column vector:
 [[10 11 12]
 [23 24 25]]
Add row vector:
 [[100 201 302]
 [103 204 305]]
Outer sum via broadcasting:
 [[110 210 310]
 [120 220 320]]



## 4) Aggregations & Axes

Use `axis` to control **which dimension you reduce over**.


In [8]:

Y = np.arange(1,13).reshape(3,4)
print("Y:\n", Y)
print("Sum (all):", Y.sum())
print("Sum over rows (axis=1):", Y.sum(axis=1))
print("Mean over columns (axis=0):", Y.mean(axis=0))
print("Min/Max:", Y.min(), Y.max())
print("Argmax indices (axis=1):", Y.argmax(axis=1))


Y:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum (all): 78
Sum over rows (axis=1): [10 26 42]
Mean over columns (axis=0): [5. 6. 7. 8.]
Min/Max: 1 12
Argmax indices (axis=1): [3 3 3]
