# PCA Tutorial Using the Iris Dataset
This notebook teaches students how PCA works, step-by-step, including standardization, covariance, eigenvalues, projection, and reconstruction.

## 1. Load and Standardize Data

In [6]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Load iris data
iris = load_iris()
X = iris.data  # (150, 4)

# Standardize
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

X_std[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

## 2. Covariance Matrix

In [7]:
cov_mat = np.cov(X_std.T)
cov_mat

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

## 3. Eigenvalues and Eigenvectors

In [8]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvalues:', eig_vals)
print('\nEigenvectors:\n', eig_vecs)

Eigenvalues: [2.93808505 0.9201649  0.14774182 0.02085386]

Eigenvectors:
 [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


## 4. Sort Eigenvalues

In [9]:
idx = np.argsort(eig_vals)[::-1]
eig_vals_sorted = eig_vals[idx]
eig_vecs_sorted = eig_vecs[:, idx]

eig_vals_sorted

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

## 5. PCA Projection (k=2)

In [10]:
k = 2
W = eig_vecs_sorted[:, :k]
X_pca = X_std @ W
X_pca[:5]

array([[-2.26470281, -0.4800266 ],
       [-2.08096115,  0.67413356],
       [-2.36422905,  0.34190802],
       [-2.29938422,  0.59739451],
       [-2.38984217, -0.64683538]])

@ performs matrix multiplication according to linear algebra rules.

A @ B   ==   np.matmul(A, B)   ==   A.dot(B)

## 6. Reconstruction from 2 PCs

In [11]:
X_reconstructed = X_pca @ W.T
X_reconstructed_original = scaler.inverse_transform(X_reconstructed)

X_reconstructed_original[:5]

array([[5.01894899, 3.51485426, 1.46601281, 0.25192199],
       [4.73846304, 3.03043329, 1.60391283, 0.27207352],
       [4.72013023, 3.19683002, 1.3289608 , 0.16741379],
       [4.66843611, 3.08676967, 1.38417005, 0.18224698],
       [5.01709266, 3.5964018 , 1.34541075, 0.20670563]])

## 7. Compare Original and Reconstructed

In [12]:
print('Original data (first 5 rows):')
print(X[:5])

print('\nReconstructed data (first 5 rows):')
print(X_reconstructed_original[:5])

Original data (first 5 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Reconstructed data (first 5 rows):
[[5.01894899 3.51485426 1.46601281 0.25192199]
 [4.73846304 3.03043329 1.60391283 0.27207352]
 [4.72013023 3.19683002 1.3289608  0.16741379]
 [4.66843611 3.08676967 1.38417005 0.18224698]
 [5.01709266 3.5964018  1.34541075 0.20670563]]
