## 1. 创建 Series 的几种方式

In [1]:
import numpy as np
import pandas as pd

#### 1. 通过列表或者元组创建 Series

In [2]:
data = [10,20,30,40,50] # 也可以使用元组
s_1 = pd.Series(data, dtype=np.int32)
print(s_1)
print(s_1.index)
print(s_1.values)
print(s_1.dtype)

0    10
1    20
2    30
3    40
4    50
dtype: int32
RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
int32


#### 2. 通过 ndarray 创建 Series

In [4]:
arr = np.array(["a", "b", "c", "d"])
s_2 = pd.Series(arr, dtype=np.object_)
print(s_2)
print(s_2.index)
print(s_2.values)
print(s_2.dtype)

0    a
1    b
2    c
3    d
dtype: object
RangeIndex(start=0, stop=4, step=1)
['a' 'b' 'c' 'd']
object


#### 3. 通过手动指定index创建 Series

In [5]:
arr_2 = np.array([1.5, 2.5, 3.5, 4.5], dtype=np.float32)
s_3 = pd.Series(arr_2, dtype=np.float32, index=["a", "b", "c", "d"])
print(s_3)
print(s_3.index)
print(s_3.values)
print(s_3.dtype)

a    1.5
b    2.5
c    3.5
d    4.5
dtype: float32
Index(['a', 'b', 'c', 'd'], dtype='object')
[1.5 2.5 3.5 4.5]
float32


#### 4. 通过dict创建 Series，key作为index，value作为数据

In [6]:
dict_1 = {"a": 100, "b": 200, "c": 300, "d": 400}
s_4 = pd.Series(dict_1, dtype=np.int32)
print(s_4)
print(s_4.index)
print(s_4.values)
print(s_4.dtype)

a    100
b    200
c    300
d    400
dtype: int32
Index(['a', 'b', 'c', 'd'], dtype='object')
[100 200 300 400]
int32


#### 5. 指定name属性创建 Series

In [7]:
dict_2 = {
    "Tom": 18,
    "Jack": 20,
    "Steve": 25,
    "Ricky": 30
}
s_5 = pd.Series(dict_2, dtype=np.int32, name="Age of Employees")
print(s_5)
print(s_5.index)
print(s_5.values)
print(s_5.dtype)
print(s_5.name)

Tom      18
Jack     20
Steve    25
Ricky    30
Name: Age of Employees, dtype: int32
Index(['Tom', 'Jack', 'Steve', 'Ricky'], dtype='object')
[18 20 25 30]
int32
Age of Employees
