## 1.ndarray的特性与属性

#### 1. 引入numpy


In [ ]:
import numpy as np

#### 2. ndarray的特性

##### 2.1 多维性

In [17]:
arr_0d = np.array(5) # 创建0维数组, 值为5
print(arr_0d)

arr_1d = np.array([1,2,3,4,5]) # 创建1维数组
print(arr_1d)

arr_2d = np.array([
    [1,2,3],
    [4,5,6]]) # 创建2维数组,每一个元素为一个1维数组
print(arr_2d)

arr_3d = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]]) # 创建3维数组，每一个元素为一个2维数组
print(arr_3d)

5
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


##### 2.2 同质性

In [13]:
arr_flot = np.array([1.0, 2.0, 3.0]) # 创建浮点型数组
print("Type of arr_flot:", arr_flot.dtype)

Type of arr_flot: float64


In [15]:
arr_mix = np.array([1, 'hello']) # 1 会被转换为字符串
print(arr_mix)
print("Type of arr_mix:", arr_mix.dtype)

['1' 'hello']
Type of arr_mix: <U21


#### 3. ndarray的属性，不是方法，所以使用时不加括号

##### 3.1 ndim: 维度数

In [18]:
print("Dimension of arr_0d:", arr_0d.ndim)
print("Dimension of arr_1d:", arr_1d.ndim)
print("Dimension of arr_2d:", arr_2d.ndim)
print("Dimension of arr_3d:", arr_3d.ndim)

Dimension of arr_0d: 0
Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3


##### 3.2 shape: 形状

In [20]:
print("Shape of arr_0d:", arr_0d.shape)
print("Shape of arr_1d:", arr_1d.shape) # 注意：是 (5,) 而不是 (5)
print("Shape of arr_2d:", arr_2d.shape)
print("Shape of arr_3d:", arr_3d.shape)

Shape of arr_0d: ()
Shape of arr_1d: (5,)
Shape of arr_2d: (2, 3)
Shape of arr_3d: (3, 3, 3)


##### 3.3 size: 元素总数

In [21]:
print("Size of arr_0d:", arr_0d.size)
print("Size of arr_1d:", arr_1d.size)
print("Size of arr_2d:", arr_2d.size)
print("Size of arr_3d:", arr_3d.size)

Size of arr_0d: 1
Size of arr_1d: 5
Size of arr_2d: 6
Size of arr_3d: 27


##### 3.4 itemsize & nbytes: 元素字节大小 & 数组总字节大小

In [24]:
print("Itemsize of arr_0d:", arr_0d.itemsize, "because dtype is:", arr_0d.dtype, ", so each element takes 64/8=8 bytes")
print("Total bytes of arr_3d:", arr_3d.size * arr_3d.itemsize)
print("Nbytes of arr_3d:", arr_3d.nbytes)

Itemsize of arr_0d: 8 because dtype is: int64 , so each element takes 64/8=8 bytes
Total bytes of arr_3d: 216
Nbytes of arr_3d: 216
