## 4. ndarray的索引和切片

In [1]:
import numpy as np

#### 1. 一维索引和切片

In [2]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


##### 1.1 索引

In [3]:
print("Element at index 5:", arr_1d[5])

Element at index 5: 6


##### 1.2 切片

In [ ]:
print("Elements from index 2 - 5:", arr_1d[2:5:1]) # start:inclusive, stop: exclusive,step:default 1
print("Elements from index 0 - 8 with step 2:", arr_1d[0:8:2])

#### 2. 二维索引和切片

In [6]:
arr_2d = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
], dtype=np.int32)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


##### 2.1 索引,先行后列

In [7]:
print("Element at row 1, column 3:", arr_2d[1,3]) # 注意：行列索引均从0开始
print("Element at row 2, column 4:", arr_2d[2,4])

Element at row 1, column 3: 9
Element at row 2, column 4: 15


##### 2.2 切片, 先行后列

In [8]:
print("Elements from row 0-2, column 2-5:", arr_2d[0:2:1, 2:5:1]) # 行切片0-2，列切片2-5

Elements from row 0-2, column 2-5: [[ 3  4  5]
 [ 8  9 10]]


#### 3. 切片的返回值： 视图(view) vs 副本(copy)

##### 3.1 视图(view): 切片返回的是原ndarray的视图，对视图的修改会影响原ndarray

In [9]:
sub = arr_1d[2:5:1]
sub[0] = 100
print(arr_1d)

[  1   2 100   4   5   6   7   8   9  10]


##### 3.2 副本(copy): 使用 np.copy() 创建ndarray的副本，对副本的修改不会影响原ndarray

In [10]:
sub = arr_2d[0:2:1, 2:5:1].copy()
sub[0,0] = 1000
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### 4. 花式索引(fancy indexing)
**花式索引是直接传递一个一维或者二维索引列表**
返回值不是视图(view)，而是**副本(copy)**

##### 4.1 对一维 ndarray（只能传递给一维ndarray）

In [11]:
arr_3 = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)
sub_1 = arr_3[[1,5]] # 获取索引为1和5的元素，注意：不是切片，不是1-5的范围
print(sub_1)

[2 6]


##### 4.2 对二维 ndarray 使用索引列表

In [13]:
arr_4 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
], dtype=np.int32)

sub_2 = arr_4[[0,2]] # 表示点名获取 第0行第2行的元素
print(sub_2)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [16]:
sub_3 = arr_4[[0,2], [1,3]]
# [0,2] 表示0行2列
# [1,3] 表示1行3列
# 最终结果为 [arr_4[0,1], arr_4[2,3]] => [2,14]
print(sub_3)

[ 2 14]


#### 5. 布尔索引(Boolean Indexing)
**布尔索引是传递一个判断条件，返回符合条件的元素组成的新ndarray**
**返回值不是视图(view)，而是副本(copy)**

In [19]:
arr_5 = np.array([10,15,20,25,30,35,40,45,50], dtype=np.int32)
sub_4 = arr_5[arr_5 > 30] # 获取大于30的元素
print(sub_4)

[35 40 45 50]
